//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMic_QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DMMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DMMonHoc()
        {
            this.tbl_Diem = new HashSet<tbl_Diem>();
        }
    
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public string Khoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Diem> tbl_Diem { get; set; }
    }
}
