//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iMic_QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SinhVien()
        {
            this.tbl_Diem = new HashSet<tbl_Diem>();
        }
    
        public string MSSV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NTNS { get; set; }
        public string NoiSinh { get; set; }
        public string MaKhoa { get; set; }
        public Nullable<bool> KetQuaTN { get; set; }
        public Nullable<double> DTB { get; set; }
        public string XepLoaiTN { get; set; }
        public Nullable<bool> isUserLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Diem> tbl_Diem { get; set; }
        public virtual tbl_Khoa tbl_Khoa { get; set; }
    }
}
